
environment:
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7.x" # currently 2.7.9
          PYTHON_ARCH: "32"

version: 1.0.{build}
branches:
    only:
        - test-appveyor
    
install:
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Check that we have the expected version and architecture for Python
    - "python --version"
    - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

    # Upgrade to the latest version of pip to avoid it displaying warnings
    # about it being out of date.
    - "pip install --disable-pip-version-check --user --upgrade pip"  
    - "pip install -r dev-requirements.txt"
    - "pip install tox"

build: off

test_script:
    - ps: tox